// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelsManga.DataAccess.Data;


#nullable disable

namespace NovelsManga.DataAccess.Migrations
{
    [DbContext(typeof(MangaNovelDatabase))]
    [Migration("20240626084922_AddingToDb")]
    partial class AddingToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovelsAndManga.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("NovelsAndManga.Models.NovelsGenre", b =>
                {
                    b.Property<int>("NovelsId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("NovelsId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("novelsGenres");
                });

            modelBuilder.Entity("NovelsAndManga.Models.NovelsModels", b =>
                {
                    b.Property<int>("NovelsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NovelsId"));

                    b.Property<string>("NovelsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovelsSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NovelsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NovelsId");

                    b.ToTable("NovelsPage");
                });

            modelBuilder.Entity("NovelsAndManga.Models.NovelsGenre", b =>
                {
                    b.HasOne("NovelsAndManga.Models.Genre", "Genre")
                        .WithMany("NovelGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovelsAndManga.Models.NovelsModels", "Novel")
                        .WithMany("NovelGenres")
                        .HasForeignKey("NovelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("NovelsAndManga.Models.Genre", b =>
                {
                    b.Navigation("NovelGenres");
                });

            modelBuilder.Entity("NovelsAndManga.Models.NovelsModels", b =>
                {
                    b.Navigation("NovelGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
